#!/usr/bin/env zsh

##############################################################################

CMD = "pipenv run python audgod.py"

MUSIC_FOLDER = "${HOME}/Music"
MUSIC_SOURCE_FOLDER = "${MUSIC_FOLDER}/Source"
MUSIC_GROUPED_FOLDER = "${MUSIC_FOLDER}/Grouped"
MUSIC_ARTWORKS_FOLDER = "${MUSIC_FOLDER}/Artworks"

ITUNES_FOLDER = "${MUSIC_FOLDER}/iTunes"
ITUNES_MEDIA_FOLDER = "${ITUNES_FOLDER}/iTunes\ Media"
ITUNES_LIBRARY_PLIST = "${ITUNES_MEDIA_FOLDER}/Library.xml"
ITUNES_VERSION_PLIST = "/System/Applications/Music.app/Contents/version.plist"

LOCAL_FOLDER = "${PWD}"

IGNORED_FILE = "${LOCAL_FOLDER}/ignored.txt"
NOTE_FILE = "${LOCAL_FOLDER}/songs.note"
REPEATED_FILE = "${LOCAL_FOLDER}/repeated.txt"

EXTENSIONS = "mp3,aac"
FILENAME_PATTERN = "@{artist} # @{title}"

LOG_LEVEL = "WARNING"
LOG_FILE = "stderr"

##############################################################################

function preprocess-notes() {
    ${CMD} preprocess-notes \
        --source-file=${NOTE_FILE} \
        --field-type=cn \
        --log-level=${LOG_LEVEL} \
        --log-file=${LOG_FILE}
}

function fill-properties() {
    ${CMD} fill-properties \
        --audios-source=${MUSIC_SOURCE_FOLDER} \
        --extensions=${EXTENSIONS} \
        --recursive \
        --ignored-file=${IGNORED_FILE} \
        --source-file=${NOTE_FILE} \
        --audios-root=${MUSIC_SOURCE_FOLDER} \
        --log-level=${LOG_LEVEL} \
        --log-file=${LOG_FILE}
}

function format-properties() {
    ${CMD} format-properties \
        --audios-source=${MUSIC_SOURCE_FOLDER} \
        --extensions=${EXTENSIONS} \
        --recursive \
        --ignored-file=${IGNORED_FILE} \
        --log-level=${LOG_LEVEL} \
        --log-file=${LOG_FILE}
}

function rename-audios() {
    ${CMD} rename-audios \
        --audios-source=${MUSIC_SOURCE_FOLDER} \
        --extensions=${EXTENSIONS} \
        --recursive \
        --ignored-file=${IGNORED_FILE} \
        --filename-pattern="${FILENAME_PATTERN}" \
        --log-level=${LOG_LEVEL} \
        --log-file=${LOG_FILE}
}

function organize-grouped-files() {
    ${CMD} organize-files \
        --audios-source=${MUSIC_SOURCE_FOLDER} \
        --extensions=${EXTENSIONS} \
        --recursive \
        --ignored-file=${IGNORED_FILE} \
        --audios-root=${MUSIC_GROUPED_FOLDER} \
        --organize-type=grouped \
        --log-level=${LOG_LEVEL} \
        --log-file=${LOG_FILE}
}

function organize-ituned-files() {
    ${CMD} organize-files \
        --audios-source=${MUSIC_SOURCE_FOLDER} \
        --extensions=${EXTENSIONS} \
        --recursive \
        --ignored-file=${IGNORED_FILE} \
        --audios-root=${ITUNES_MEDIA_FOLDER} \
        --organize-type=ituned \
        --log-level=${LOG_LEVEL} \
        --log-file=${LOG_FILE}
}

function organize-files() {
    organize-grouped-files & \
    organize-ituned-files
}

function list-repeated() {
    ${CMD} list-repeated \
        --audios-source=${MUSIC_GROUPED_FOLDER} \
        --extensions=${EXTENSIONS} \
        --recursive \
        --ignored-file=${IGNORED_FILE} \
        --output-file=${REPEATED_FILE} \
        --log-level=${LOG_LEVEL} \
        --log-file=${LOG_FILE}
}

function export-note() {
    ${CMD} export \
        --audios-source=${MUSIC_GROUPED_FOLDER} \
        --extensions=${EXTENSIONS} \
        --recursive \
        --ignored-file=${IGNORED_FILE} \
        --fields=note \
        --field-type=cn \
        --output-format=note \
        --output-file=${NOTE_FILE} \
        --log-level=${LOG_LEVEL} \
        --log-file=${LOG_FILE}
}

function export-plist() {
    ${CMD} export \
        --audios-source=${ITUNES_MEDIA_FOLDER} \
        --extensions=${EXTENSIONS} \
        --recursive \
        --ignored-file=${IGNORED_FILE} \
        --fields=ituned \
        --field-type=en \
        --itunes-version-plist=${ITUNES_VERSION_PLIST} \
        --itunes-media-folder=${ITUNES_MEDIA_FOLDER} \
        --track-initial-id=601 \
        --playlist-initial-id=3001 \
        --output-format=plist \
        --output-file=${ITUNES_LIBRARY_PLIST} \
        --log-level=${LOG_LEVEL} \
        --log-file=${LOG_FILE}
}

function export() {
    export-plist & \
    export-note
}

function derive-artworks() {
    ${CMD} derive-artworks \
        --audios-source=${MUSIC_SOURCE_FOLDER} \
        --extensions=${EXTENSIONS} \
        --recursive \
        --ignored-file=${IGNORED_FILE} \
        --artwork-path=${MUSIC_ARTWORK_FOLDER} \
        --log-level=${LOG_LEVEL} \
        --log-file=${LOG_FILE}
}

function convert() {
    ${CMD} convert \
        --audios-source=${MUSIC_SOURCE_FOLDER} \
        --extensions=${EXTENSIONS} \
        --recursive \
        --ignored-file=${IGNORED_FILE} \
        --log-level=${LOG_LEVEL} \
        --log-file=${LOG_FILE}
}

function display() {
}

##############################################################################

function main() {
    #pipenv run python audgod.py "$@"
    preprocess-notes & \
    fill-properties & \
    format-properties & \
    rename-audios & \
    organize-grouped-files & \
    export-note & \
    list-repeated & \
    organize-ituned-files & \
    export-plist
}

##############################################################################

main "$@"
